json This workflow will trigger Datadog Synthetic tests within your Datadog organisation
json For more information on running Synthetic tests within your GitHub workflows see: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

json This workflow uses actions that are not certified by GitHub.
json They are provided by a third-party and are governed by
json separate terms of service, privacy policy, and support
json documentation.
json:
  started:
   Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see: https://docs.datadoghq.com/account_management/api-app-keys/.
           : Start using the action within your workflow

name): Run Datadog Synthetic tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

jobs:
  For additional configuration options visit the action within the marketplace: https://github.com/marketplace/actions/datadog-synthetics-ci
    name: Run Datadog Synthetic tests
     uses: DataDog/synthetics-ci-github-action@2b56dc0cca9daa14ab69c0d1d6844296de8f941e
      with:
        api_key: ${{secrets.DD_API_KEY}}
        app_key: ${{secrets.DD_APP_KEY}}
        test_search_query: 'tag:e2e-tests' jsonModify this tag to suit your tagging strategy
        json:
16/personalities: 
  8/Personalities:
     /traits: